#!/usr/bin/env node
/**
 * Generates public/firebase-messaging-sw.js from .env.local + package.json.
 * Runs automatically before `npm run dev` and `npm run build`.
 *
 * The SW can't read env vars at runtime, so we bake them in at build time.
 * The values are NEXT_PUBLIC_* so they're not secret.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const envPath = join(root, ".env.local");
const outPath = join(root, "public", "firebase-messaging-sw.js");
const pkgPath = join(root, "package.json");

function readEnvLocal(file) {
  if (!existsSync(file)) return {};
  const text = readFileSync(file, "utf8");
  const env = {};
  for (const line of text.split(/\r?\n/)) {
    if (!line || line.startsWith("#")) continue;
    const m = line.match(/^([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (!m) continue;
    let value = m[2].trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[m[1]] = value;
  }
  return env;
}

// In local dev .env.local has the values; in CI / Firebase App Hosting build,
// the values come in via process.env (declared in apphosting.yaml or set in the
// Firebase Console). Merge with .env.local taking precedence so devs can override.
const env = { ...process.env, ...readEnvLocal(envPath) };
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const firebaseDep = pkg.dependencies?.firebase ?? "12.13.0";
const firebaseVersion = firebaseDep.replace(/^[\^~]/, "");

const config = {
  apiKey: env.NEXT_PUBLIC_FIREBASE_API_KEY ?? "",
  authDomain: env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? "",
  projectId: env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? "",
  storageBucket: env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ?? "",
  messagingSenderId: env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? "",
  appId: env.NEXT_PUBLIC_FIREBASE_APP_ID ?? "",
};

const missing = Object.entries(config)
  .filter(([, v]) => !v)
  .map(([k]) => k);

if (missing.length > 0) {
  console.warn(
    `[generate-fcm-sw] Missing env vars for: ${missing.join(", ")} — SW will be written with empty values. Push won't work until you fill .env.local.`,
  );
}

const sw = `// Generated by scripts/generate-fcm-sw.mjs — do not edit by hand.
// Re-runs before \`npm run dev\` and \`npm run build\`.

importScripts("https://www.gstatic.com/firebasejs/${firebaseVersion}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${firebaseVersion}/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(config, null, 2)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title = (payload.notification && payload.notification.title) || "Mango Pet";
  const options = {
    body: (payload.notification && payload.notification.body) || "",
    icon: (payload.notification && payload.notification.icon) || "/web-app-manifest-192x192.png",
    badge: "/favicon-96x96.png",
    data: payload.data || {},
  };
  self.registration.showNotification(title, options);
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const target = (event.notification.data && event.notification.data.url) || "/app";
  event.waitUntil(
    clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((list) => {
        for (const client of list) {
          if (client.url.includes(target) && "focus" in client) return client.focus();
        }
        if (clients.openWindow) return clients.openWindow(target);
      }),
  );
});
`;

writeFileSync(outPath, sw, "utf8");
console.log(`[generate-fcm-sw] wrote ${outPath} (firebase ${firebaseVersion})`);
